# Generated by Django 2.0 on 2019-03-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canteenmodel',
            options={'permissions': (('edit_сanteen', 'Edit Canteen'),), 'verbose_name': 'Столовая'},
        ),
    ]
