# Generated by Django 2.0 on 2019-03-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0008_remove_dishmodel_canteen'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishmodel',
            name='timefinish',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='dishmodel',
            name='timestart',
            field=models.TimeField(null=True),
        ),
    ]
