# Generated by Django 2.0 on 2019-03-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0009_auto_20190318_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishmodel',
            name='timefinish',
        ),
        migrations.RemoveField(
            model_name='dishmodel',
            name='timestart',
        ),
        migrations.AddField(
            model_name='canteenmodel',
            name='timefinish',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='canteenmodel',
            name='timestart',
            field=models.TimeField(null=True),
        ),
    ]
