# Generated by Django 2.0 on 2019-03-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0010_auto_20190318_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteenmodel',
            name='timefinish',
        ),
        migrations.RemoveField(
            model_name='canteenmodel',
            name='timestart',
        ),
        migrations.AddField(
            model_name='canteenmodel',
            name='description',
            field=models.TextField(default='', max_length=100, verbose_name='описание'),
        ),
    ]
