# Generated by Django 2.0 on 2019-03-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0008_auto_20190319_0104'),
        ('canteen', '0011_auto_20190318_2002'),
    ]

    operations = [
    ]
